### ISSUE TITLE
question re: pi-hole + vpn

### ISSUE THREAD

**Issue by kronflux** [CHEF-KOCH/CK-s-Raspberry-Pi-3-config#2]
Based on the readme, I'm pretty sure this is the case, but where I have limited experience with pi-hole, is it safe to assume that the VPN pushes it's requests through pi-hole? ie: anywhere in the world I'm connected to my VPN on any device, the pi-hole would be blocking ads?

**Comment by CHEF-KOCH** [comment]
Nothing is "safe" not even a VPN but I try to answer the question.

1.) Some VPN providers already blocking ads e.g. PIA (called MACE")
2.) Most ads are these days delivered via HTTPS which requires some inspection, this alone is more or less dangerous because tools like adguard or others inspecting them (requires a certificate to "re-"direct them) which possible allows to abuse it (Android/Windows already wars but the hole is _theortically_ possible). However, https are more difficult to filter (blocking is no problem).
3.) If you set-up the pi-hole correctly the dns traffic should go over the Pi, this allows already to filter (faster) the requests compared top re-directing them first. 
4.) Most people have "slow-downs" because of 3. you have to ensure you use on the OS (Windows/Linux/etc) the DNS address from the Pi-Hole otherwise the OS still tries to connect the VPN server on each request, this roundtrip is significantly slower since the PI gets triggered again.

**Comment by kronflux** [comment]
sorry, perhaps I wasn't entirely clear in my question.
I wasn't asking about security, I was asking if I'm correct in assuming that this setup makes all devices connected to the VPN use Pi-Hole by default.

So all devices connected to the VPN being hosted by the pi, also benefit from pi-hole - correct?

**Comment by CHEF-KOCH** [comment]
Yep.
